name: continuous

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Restore and build
        shell: pwsh
        run: |
          ./build.ps1

  publish:
    needs: build
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    environment:
      name: default
    steps:
      - uses: actions/checkout@v3

      - name: Publish
        shell: pwsh
        run: |
          pack.ps1
          dotnet nuget push --source "https://api.nuget.org/v3/index.json" --api-key="${{ env.NODE_VERSION }}" ~/artifacts/*.nupkg
