name: continuous

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Restore and build
        shell: pwsh
        run: |
          ./build.ps1

  publish:
    needs: build
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    environment:
      name: default
      url: https://www.nuget.org/packages/Xerris.DotNet.Templates
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Publish
        shell: pwsh
        env:
          NUGET_APIKEY: ${{ secrets.NUGET_APIKEY_PUSH }}
        run: |
          ./pack.ps1
          dotnet nuget push ./artifacts/*.nupkg --source "https://api.nuget.org/v3/index.json" --api-key "$env:NUGET_APIKEY_PUSH"
